/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-18-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class AccountHandler {
   
    /**
    * @description 
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-18-2025 
    **/
    public AccountHandler() {
            string s = '3';
        for(integer i = 0 ; i<10 ; i++){
             
        }
        if(true){

        }else{

        }
    }
}